version: '3'

services:
  app:
    build: .
    ports:
     - "5001:8000"
    volumes:
     - .:/app
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin 
      - MYSQL_DB=test

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin
      - MYSQL_DB=test
      - MYSQL_ROOT_PASSWORD=admin

    ports:
      - "3306:3306"